# Generated by Django 4.1.2 on 2022-11-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0003_alter_gg_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gg',
            name='img',
            field=models.ImageField(upload_to='cc'),
        ),
    ]
