# Generated by Django 4.1.2 on 2023-01-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0004_alter_gg_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('total_cards', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='GG',
        ),
    ]
